# Generated by Django 4.2.1 on 2023-05-22 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_dislikes', to='blogs.blog'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='type',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')]),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
