# Generated by Django 4.2.1 on 2023-05-22 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_alter_likedislike_blog_alter_likedislike_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together={('blog', 'user')},
        ),
    ]
